#!/usr/bin/env bash
# This script displays "To infinity and beyond" and handles SIGTERM

# Set up SIGTERM handler
trap 'echo "I am invincible!!!"' TERM

# Infinite loop
while :
do
    echo "To infinity and beyond"
    sleep 2 &
    wait $!
done
