#!/usr/bin/env bash
# This script displays "To infinity and beyond" and handles SIGTERM

# Trap SIGTERM signal to display message but continue
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
